/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BassoRouteImport } from './routes/basso'
import { Route as KannelRouteImport } from './routes/kannel'
import { Route as KitaraRouteImport } from './routes/kitara'
import { Route as UkuleleRouteImport } from './routes/ukulele'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BassoRoute = BassoRouteImport.update({
  id: '/basso',
  path: '/basso',
  getParentRoute: () => rootRouteImport,
} as any)
const KannelRoute = KannelRouteImport.update({
  id: '/kannel',
  path: '/kannel',
  getParentRoute: () => rootRouteImport,
} as any)
const KitaraRoute = KitaraRouteImport.update({
  id: '/kitara',
  path: '/kitara',
  getParentRoute: () => rootRouteImport,
} as any)
const UkuleleRoute = UkuleleRouteImport.update({
  id: '/ukulele',
  path: '/ukulele',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basso': typeof BassoRoute
  '/kannel': typeof KannelRoute
  '/kitara': typeof KitaraRoute
  '/ukulele': typeof UkuleleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basso': typeof BassoRoute
  '/kannel': typeof KannelRoute
  '/kitara': typeof KitaraRoute
  '/ukulele': typeof UkuleleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basso': typeof BassoRoute
  '/kannel': typeof KannelRoute
  '/kitara': typeof KitaraRoute
  '/ukulele': typeof UkuleleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/basso' | '/kannel' | '/kitara' | '/ukulele'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basso' | '/kannel' | '/kitara' | '/ukulele'
  id: '__root__' | '/' | '/basso' | '/kannel' | '/kitara' | '/ukulele'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BassoRoute: typeof BassoRoute
  KannelRoute: typeof KannelRoute
  KitaraRoute: typeof KitaraRoute
  UkuleleRoute: typeof UkuleleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basso': {
      id: '/basso'
      path: '/basso'
      fullPath: '/basso'
      preLoaderRoute: typeof BassoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kannel': {
      id: '/kannel'
      path: '/kannel'
      fullPath: '/kannel'
      preLoaderRoute: typeof KannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitara': {
      id: '/kitara'
      path: '/kitara'
      fullPath: '/kitara'
      preLoaderRoute: typeof KitaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukulele': {
      id: '/ukulele'
      path: '/ukulele'
      fullPath: '/ukulele'
      preLoaderRoute: typeof UkuleleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BassoRoute: BassoRoute,
  KannelRoute: KannelRoute,
  KitaraRoute: KitaraRoute,
  UkuleleRoute: UkuleleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
